# Generated by Django 4.2 on 2023-05-09 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("driving_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("designation", models.TextField(max_length=45)),
                ("feedback", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
