# Generated by Django 4.2 on 2023-05-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("driving_app", "0004_alter_trainer_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program_details",
            fields=[
                (
                    "program_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("charges", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle_model",
            fields=[
                (
                    "modelname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("seater", models.CharField(max_length=45)),
                ("fuel_type", models.CharField(max_length=45)),
                ("vehicle_type", models.CharField(max_length=45)),
                ("other_details", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="trainer", name="address", field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Vehicle_details",
            fields=[
                (
                    "vehicle_no",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("color", models.CharField(max_length=45)),
                ("device_no", models.CharField(max_length=45)),
                (
                    "vehicle_pic",
                    models.FileField(
                        default="", upload_to="driving_app/vehicle_picture"
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="driving_app.vehicle_model",
                    ),
                ),
            ],
        ),
    ]
