# Generated by Django 4.2 on 2023-05-13 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "driving_app",
            "0005_program_details_vehicle_model_alter_trainer_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("transaction_no", models.CharField(max_length=45)),
                ("transaction_id", models.CharField(max_length=45, null=True)),
                ("password", models.CharField(max_length=45, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driving_app.program_details",
                    ),
                ),
                (
                    "trainer",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driving_app.trainer",
                    ),
                ),
            ],
        ),
    ]
