# Generated by Django 4.2 on 2023-05-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driving_app", "0006_trainee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainee", old_name="transaction_id", new_name="trainee_id",
        ),
    ]
