# Generated by Django 4.2 on 2023-05-22 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driving_app', '0008_alter_trainee_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('trainer', models.CharField(max_length=45)),
                ('trainee', models.CharField(max_length=45)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('performance', models.TextField()),
                ('vehicle_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='driving_app.vehicle_details')),
            ],
        ),
    ]
